algoritmo "bitcoin"
// Função :  calcular bitcoins
// Autor : Nagela Renata Lima Rosário
// Data : 07/01/2022
// Seção de Declarações 
var
   nome: caractere
   v1, v2, c, resultado: real
inicio
// Seção de Comandos
   Escreva("Qual é seu nome? ")
   Leia(nome)
   Escreva("Digite a primeira variável: ")
   Leia(v1)
   Escreva("Digite a segunda variável: ")
   Leia(v2)
   c <- 2.15
   resultado <- v1 * v2 * c
   Escreva(nome, ", o resultado é", resultado)
   
fimalgoritmo
