algoritmo "cont"
// Função :
// Autor :
// Data : 17/10/2021
// Seção de Declarações 
var
valor, salto, contador: inteiro
inicio
// Seção de Comandos
   contador <- 0
   Escreva("Até quantos você quer contar? ")
   Leia(valor)
   Escreva("De quanto em quanto você que pular? ")
   Leia(salto)
   Enquanto (contador <= valor) faca
            Escreval(contador)
            contador <- contador + salto
   Fimenquanto
fimalgoritmo
