algoritmo "SomaParametrosReferencia"
// Função :
// Autor :
// Data : 20/01/2022
// Seção de Declarações 
var
   X, Y: inteiro
Procedimento Soma (A, B: Inteiro)
inicio
      A <- A + 1
      B <- B + 2
      EscrevaL("Valor de A = ", A)
      EscrevaL("Valor de B = ", B)
      EscrevaL("Valor de A + B = ", A+B)
FimProcedimento
inicio
// Seção de Comandos
   X <- 4
   Y <- 8
   Soma (X, y)
   EscrevaL("Valor de X = ", X)
   EscrevaL("Valor de Y = ", Y)
fimalgoritmo
